const images4 = [
    "assets/images/ports/p (1).jpeg",
    "assets/images/ports/p (2).jpeg",
    "assets/images/ports/p (3).jpeg",
    "assets/images/ports/p (4).jpeg",
    "assets/images/ports/p (5).jpeg",
    "assets/images/ports/p (6).jpeg",
    "assets/images/ports/p (7).jpeg",
    "assets/images/ports/p (8).jpeg",
    "assets/images/ports/p (9).jpeg",
    "assets/images/ports/p (10).jpeg",
    "assets/images/ports/p (11).jpeg",
    "assets/images/ports/p (12).jpeg",
    "assets/images/ports/p (13).jpeg",
    "assets/images/ports/p (14).jpeg",
    "assets/images/ports/p (15).jpeg",
    "assets/images/ports/p (16).jpeg",
    "assets/images/ports/p (17).jpeg",
    "assets/images/ports/p (18).jpeg",
    "assets/images/ports/p (19).jpeg",
    "assets/images/ports/p (20).jpeg",
    "assets/images/ports/p (21).jpeg",
    "assets/images/ports/p (22).jpeg",
    "assets/images/ports/p (23).jpeg",
    "assets/images/ports/p (24).jpeg",
    "assets/images/ports/p (25).jpeg",
    "assets/images/ports/p (26).jpeg",
    "assets/images/ports/p (27).jpeg",
    "assets/images/ports/p (28).jpeg",
    "assets/images/ports/p (29).jpeg",
    "assets/images/ports/p (30).jpeg",
    "assets/images/ports/p (31).jpeg",
    "assets/images/ports/p (32).jpeg",
    "assets/images/ports/p (33).jpeg",
    "assets/images/ports/p (34).jpeg",
    "assets/images/ports/p (35).jpeg",
    "assets/images/ports/p (36).jpeg",
    "assets/images/ports/p (37).jpeg",
    "assets/images/ports/p (38).jpeg",
    "assets/images/ports/p (39).jpeg",
    "assets/images/ports/p (40).jpeg",
    "assets/images/ports/p (41).jpeg",
    "assets/images/ports/p (42).jpeg",
    "assets/images/ports/p (43).jpeg",
    "assets/images/ports/p (44).jpeg",
    "assets/images/ports/p (45).jpeg",
    "assets/images/ports/p (46).jpeg",
    "assets/images/ports/p (47).jpeg",
    "assets/images/ports/p (48).jpeg",
    "assets/images/ports/p (49).jpeg",
    "assets/images/ports/p (50).jpeg",
    "assets/images/ports/p (51).jpeg",
    "assets/images/ports/p (52).jpeg",
    "assets/images/ports/p (53).jpeg",
    "assets/images/ports/p (54).jpeg",
    "assets/images/ports/p (55).jpeg",
    "assets/images/ports/p (56).jpeg",
    "assets/images/ports/p (57).jpeg",
    "assets/images/ports/p (58).jpeg",
    "assets/images/ports/p (59).jpeg",
    "assets/images/ports/p (60).jpeg",
    "assets/images/ports/p (61).jpeg",
    "assets/images/ports/p (62).jpeg",
    "assets/images/ports/p (63).jpeg",
    "assets/images/ports/p (64).jpeg",
    "assets/images/ports/p (65).jpeg",
    "assets/images/ports/p (66).jpeg",
    "assets/images/ports/p (67).jpeg",
    "assets/images/ports/p (68).jpeg",
    "assets/images/ports/p (69).jpeg",
    "assets/images/ports/p (70).jpeg",
    "assets/images/ports/p (71).jpeg",
    "assets/images/ports/p (72).jpeg",
    "assets/images/ports/p (73).jpeg",
    "assets/images/ports/p (74).jpeg",
    "assets/images/ports/p (75).jpeg",
    "assets/images/ports/p (76).jpeg",
];
images4.forEach((src) => {
    document.write(`
        <div class="col-md-4 col-sm-6">
            <div class="single-explore-item">
                <div class="single-explore-img">
                    <img style="object-fit: cover;" src="${src}" alt="explore image">
                </div>
            </div>
        </div>
    `);
});